### ISSUE TITLE
Command palette

### ISSUE THREAD

**Issue by dajoh** [FacepunchProgrammers/ded#6]
A command palette like in Atom/Sublime/VSCode.
Ctrl+X as the keyboard shortcut maybe?

**Comment by bbielsa** [comment]
I started working on it, but there is no good way of taking focus away from the active editor. We either have to make a more generalized gui element that accepts input, or make the command palette an editor itself.

[Command palette](https://bielsa.me/dl/2016-01-31_12-15-59.png)

**Comment by Rohansi** [comment]
:eggplant: :eggplant: :eggplant: :eggplant: :eggplant: :eggplant: :eggplant: :eggplant: :eggplant: :eggplant: :eggplant: :eggplant: 

Use box characters......

**Comment by HandsomeMatt** [comment]
bbielsa is :eggplant:

**Comment by astrolantique** [comment]
Hello fellow ded contributers,

I just thought I'd give a gentle reminder that the emoji :eggplant: is extremely phallic and therefore misogynistic! @CoralineAda, anything to say about this?

Thanks,
your friendly Code of Conduct enforcement team.

**Comment by astrolantique** [comment]
@Rohansi @HandsomeMatt

**Comment by astrolantique** [comment]
HELP @CORALINEADA THEYRE DELETING ME COMMENTS DEMANDING BETTER ENFORCEMENT OF THE CODE OF CONDUCT

**Comment by astrolantique** [comment]
@FBI @CIA @DEA

**Comment by astrolantique** [comment]
@DoD

**Comment by astrolantique** [comment]
@CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda @CoralineAda

**Comment by bonnywong** [comment]
Hello @toaster468 @bbielsa can you hurry up with the action bar/gui element so that it can be used or #2. Thanks. :eggplant:

**Comment by bbielsa** [comment]
I can't do it without Dajoh setting up Ded correctly. It relies on separation of logic from ui code.
